/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Snapp.Henry.Chapter7.Java.Project;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
